<?php
namespace Geissler\CSL\Options\PageRange;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 22:29:59.
 */
class ChicagoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Chicago
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Chicago;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Options\PageRange\Chicago::format
     * @dataProvider provider
     */
    public function testFormat($input, $output)
    {
        $this->assertEquals($output, $this->object->format($input));
    }

    /**
     * @return array
     */
    public function provider()
    {
        return array(
            array('3–10', '3–10'),
            array('3–8', '3–8'),
            array('13–8', '13–18'),
            array('71–72', '71–72'),
            array('600–613', '600–613'),
            array('600–13', '600–613'),
            array('6200–13', '6200–6213'),
            array('603–604', '603–4'),
            array('1100–1123', '1100–1123'),
            array('321–325', '321–25'),
            array('321–26', '321–26'),
            array('321–7', '321–27'),
            array('415–532', '415–532'),
            array('11564–11568', '11564–68'),
            array('13792–803', '13792–13803'),
            array('1496–1504', '1496–1504'),
            array('1496–504', '1496–1504'),
            array('2787–2816', '2787–2816')
        );
    }
}
