<?php
namespace Geissler\CSL\Names;

use Geissler\CSL\Factory;
use Geissler\CSL\Container;
use Geissler\CSL\Style\Citation;
use Geissler\CSL\Style\Bibliography;
use Geissler\CSL\Data\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-05 at 14:57:24.
 */
class NameTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Name
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRender()
    {
        $layout =   '<name and="text"/>';
        $data   =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );

        $this->initElement($layout);

        $this->assertEquals('John Doe and Jane Roe', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderDelimiterAndText()
    {
        $layout =   '<name delimiter=", " and="text" />';
        $data   =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );

        $this->initElement($layout);

        $this->assertEquals('John Doe and Jane Roe', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderDelimiterAndTextInContext()
    {
        $layout     =   '<name delimiter=", " and="text" />';
        $context    =   '<citation delimiter-precedes-last="always"><layout></layout></citation>';
        $data       =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );
        $this->initElement($layout, $context);

        $this->assertEquals('John Doe, and Jane Roe', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderDelimiterAlways()
    {
        $layout =   '<name delimiter=", " and="text" delimiter-precedes-last="always"/>';
        $data   =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );

        $this->initElement($layout);

        $this->assertEquals('John Doe, and Jane Roe', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderEtAl()
    {
        $layout =   '<name delimiter=", " et-al-use-first="1" et-al-min="2"/>';
        $data   =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );
        $this->initElement($layout);

        $this->assertEquals('John Doe et al.', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderEtAl1()
    {
        $layout =   '<name delimiter=", " et-al-use-first="1" et-al-min="2" delimiter-precedes-et-al="always" />';
        $data   =   array(
            array(
                "family" =>  "Doe",
                "given" => "John"),
            array(
                "family" =>  "Roe",
                "given" => "Jane")
        );
        $this->initElement($layout);

        $this->assertEquals('John Doe, et al.', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderGreece()
    {
        $layout =   '<name and="text"/>';
        $data   =   array(
            array(
                "family" =>  "Ράις",
                "given" => "Μυρτώ")
        );

        $this->initElement($layout);

        $this->assertEquals('Ράις Μυρτώ', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderWithFormatting()
    {
        $layout =   '<name>
          <name-part name="family" text-case="uppercase"/>
        </name>';
        $data   =   array(
            array(
                "dropping-particle" => "van",
                "family" => "Meer",
                "given" => "Gerard",
                "non-dropping-particle" => "der")
        );

        $this->initElement($layout);

        $this->assertEquals('Gerard van DER MEER', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderDelimiter()
    {
        $layout =   '<name and="symbol" delimiter=", " delimiter-precedes-last="always" initialize-with="." name-as-sort-order="all" sort-separator=", " />';
        $data   =   array(
            array(
                "family"=> "O’Malley",
                "given" => "Charles D.",
                "static-ordering" => false),
            array(
                "family"=> "Saunders",
                "given" => "John Bertrand de Cusance Morant",
                "static-ordering" => false
            )
        );

        $this->initElement($layout);

        $this->assertEquals('O’Malley, C.D., &#38; Saunders, J.B. de C.M.', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderInitialize()
    {
        $layout =   '<name initialize="false" initialize-with="." />';
        $data   =   array(
            array(
                "family"=> "Kirk",
                "given" => "James T")
        );

        $this->initElement($layout);

        $this->assertEquals('James T. Kirk', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderInitialize1()
    {
        $layout =   '<name initialize="true" initialize-with=". " />';
        $data   =   array(
            array(
                "family"=> "Kirk",
                "given" => "James Tiberius")
        );

        $this->initElement($layout);

        $this->assertEquals('J. T. Kirk', $this->object->render($data));
    }

    /**
     * @covers Geissler\CSL\Names\Name::__construct
     * @covers Geissler\CSL\Names\Name::render
     * @covers Geissler\CSL\Names\Name::apply
     * @covers Geissler\CSL\Names\Name::formatName
     * @covers Geissler\CSL\Names\Name::getDisplayAndSortOrder
     */
    public function testRenderFormatted()
    {
        $layout =   '<name name-as-sort-order="all" sort-separator=" ">
                        <name-part name="family" font-variant="small-caps"/>
                        <name-part name="given" prefix="(" suffix=")"/>
                      </name>';
        $data   =   array(
            array(
                "family" => "Fontaine",
                "given" => "Jean de")
        );

        $this->initElement($layout);

        $this->assertEquals('<font style="font-variant:small-caps">Fontaine</font> (Jean de)', $this->object->render($data));
    }

    protected function initElement($layout, $context = '<citation><layout></layout></citation>', $language = 'en-US')
    {
        Container::clear();
        Container::setData(new Data());
        $locale = Factory::locale();
        $locale->readFile($language);
        Container::setLocale($locale);

        if (strpos($context, 'citation') !== false) {
            Container::getContext()->setName('citation');
            Container::setCitation(new Citation(new \SimpleXMLElement($context)));
        } else {
            Container::getContext()->setName('bibliography');
            Container::setBibliography(new Bibliography(new \SimpleXMLElement($context)));
        }

        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Name($xml);
    }
}
