language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script: phpunit --coverage-text --bootstrap tests/bootstrap.php tests/
notifications:
  email:
    - benjamin.geissler@gmail.com

