<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 16:27:14.
 */
class AffixTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Affix
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Affix::render
     * @covers Geissler\CSL\Rendering\Affix::__construct
     */
    public function testRender()
    {
        $layout = '<layout prefix="(" suffix=")" delimiter=", "><text variable="citation-number"/></layout>';
        $this->initElement($layout);
        $this->assertEquals('(test)', $this->object->render('test'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Affix::render
     */
    public function testRender1()
    {
        $layout = '<layout prefix="(" delimiter=", "><text variable="citation-number"/></layout>';
        $this->initElement($layout);
        $this->assertEquals('(test', $this->object->render('test'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Affix::render
     */
    public function testRender2()
    {
        $layout = '<layout suffix="--" delimiter=", "><text variable="citation-number"/></layout>';
        $this->initElement($layout);
        $this->assertEquals('test--', $this->object->render('test'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Affix::render
     */
    public function testDoNotRender()
    {
        $layout = '<layout prefix="(" suffix=")" delimiter=", "><text variable="citation-number"/></layout>';
        $this->initElement($layout);
        $this->assertEquals('', $this->object->render(''));
    }

    /**
     * @covers Geissler\CSL\Rendering\Affix::render
     */
    public function testDoNotRender1()
    {
        $layout = '<layout delimiter=", "><text variable="citation-number"/></layout>';
        $this->initElement($layout);
        $this->assertEquals('', $this->object->render(''));
    }

    protected function initElement($layout)
    {
        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Affix($xml);
    }
}
