<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-12 at 13:57:01.
 */
class ChildrenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Children
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Children;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Children::create
     */
    public function testCreate()
    {
        $layout  =   '<macro name="title">
                        <choose>
                          <if type="book">
                            <text variable="title" font-style="italic"/>
                          </if>
                          <else>
                            <text variable="title"/>
                          </else>
                        </choose>
                      </macro>';
        $xml    =   new \SimpleXMLElement($layout);
        $this->assertInternalType('array', $this->object->create($xml));
        $this->assertEquals(1, count($this->object->create($xml)));
        $data   =   $this->object->create($xml);
        $this->assertInstanceOf('\Geissler\CSL\Choose\Choose', $data[0]);
    }
}
