<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-13 at 15:05:56.
 */
class ExpandFormatingTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExpandFormating
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExpandFormating;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\ExpandFormating::render
     */
    public function testRender()
    {
        $this->assertEquals('<span style="font-variant:small-caps;">See</span>', $this->object->render('<sc>See</sc>'));
    }
}
