<?php
namespace Geissler\CSL\Rendering;

use Geissler\CSL\Container;
use Geissler\CSL\Data\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 16:18:57.
 */
class LayoutTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Layout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Layout;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Layout::__construct
     * @covers Geissler\CSL\Rendering\Layout::render
     */
    public function testRender()
    {
        $layout = '<layout prefix="(" suffix=")" delimiter=", "><text variable="citation-number"/></layout>';
        $json   =   '[{
            "citation-number" : 1}, {
            "citation-number" : 2}]';
        $this->initElement($layout, $json);
        $this->assertEquals('(1, 2)', $this->object->render(''));
    }

    protected function initElement($layout, $json)
    {
        $data   =   new Data();
        $data->set($json);
        Container::setData($data);

        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Layout($xml);
    }
}
