<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 18:17:26.
 */
class QuotesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Quotes
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Quotes::render
     * @covers Geissler\CSL\Rendering\Quotes::__construct
     */
    public function testRender()
    {
        $this->initElement('<text quotes="true"/>');
        $this->assertEquals('"Hello World"', $this->object->render('Hello World'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Quotes::render
     */
    public function testRender1()
    {
        $this->initElement('<text quotes="false"/>');
        $this->assertEquals('Hello World', $this->object->render('Hello World'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Quotes::render
     */
    public function testRender2()
    {
        $this->initElement('<text />');
        $this->assertEquals('Hello World', $this->object->render('Hello World'));
    }

    protected function initElement($layout)
    {
        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Quotes($xml);
    }
}
