<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 22:52:52.
 */
class TextTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Text
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Text::render
     * @covers Geissler\CSL\Rendering\Text::__construct
     */
    public function testRender()
    {
        $layout = '<text value="blue" prefix="(" suffix=")"></text>';
        $this->initElement($layout);
        $this->assertEquals('(blue)', $this->object->render('blue'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Text::render
     * @covers Geissler\CSL\Rendering\Text::__construct
     */
    public function testRender1()
    {
        $layout = '<text value="blue" prefix="(" suffix=")" text-decoration="underline"></text>';
        $this->initElement($layout);
        $this->assertEquals('(<font style="text-decoration:underline">blue</font>)', $this->object->render('blue'));
    }

    /**
     * @covers Geissler\CSL\Rendering\Text::render
     * @covers Geissler\CSL\Rendering\Text::__construct
     */
    public function testRender2()
    {
        $json = '[
    {
        "title": "His book",
        "id": "ITEM-1",
        "type": "book"
    },
    {
        "volume": "101",
        "id": "ITEM-2",
        "type": "book"
    }
]';
        \Geissler\CSL\Data\Data::set($json);

        $layout = '<text variable="title" prefix="(" suffix=")" text-decoration="underline" text-case="capitalize-first"></text>';
        $this->initElement($layout);
        $this->assertEquals('(<font style="text-decoration:underline">His book</font>)', $this->object->render('blue'));
    }

    protected function initElement($layout)
    {
        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Text($xml);
    }
}
