<?php
namespace Geissler\CSL\Rendering;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 21:32:24.
 */
class VariableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Variable
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Rendering\Variable::render
     * @covers Geissler\CSL\Rendering\Variable::__construct
     */
    public function testRender()
    {
        $json = '[
    {
        "title": "My Book",
        "edition": "5",
        "id": "ITEM-1",
        "type": "book"
    }]';
        $layout =   '<text variable="title"/>';

        $this->assertTrue(\Geissler\CSL\Data\Data::set($json));
        $this->initElement($layout);
        $this->assertEquals('My Book', $this->object->render(''));
    }

    /**
     * @covers Geissler\CSL\Rendering\Variable::render
     * @covers Geissler\CSL\Rendering\Variable::__construct
     */
    public function testRenderShort()
    {
        $json = '[
    {
        "title": "My long Book",
        "title-short" : "My Book",
        "edition": "5",
        "id": "ITEM-1",
        "type": "book"
    }]';
        $layout =   '<text variable="title" form="short"/>';

        $this->assertTrue(\Geissler\CSL\Data\Data::set($json));
        $this->initElement($layout);
        $this->assertEquals('My Book', $this->object->render(''));
    }

    /**
     * @covers Geissler\CSL\Rendering\Variable::render
     * @covers Geissler\CSL\Rendering\Variable::__construct
     */
    public function testRenderShort1()
    {
        $json = '[
    {
        "title": "My long Book",
        "edition": "5",
        "id": "ITEM-1",
        "type": "book"
    }]';
        $layout =   '<text variable="title" form="short"/>';

        $this->assertTrue(\Geissler\CSL\Data\Data::set($json));
        $this->initElement($layout);
        $this->assertEquals('My long Book', $this->object->render(''));
    }

    protected function initElement($layout)
    {
        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new Variable($xml);
    }
}
