<?php
namespace Geissler\CSL\Context;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-06 at 19:07:31.
 */
class ContextTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Context
     */
    protected $object;
    protected $class = '\Geissler\CSL\Context\Context';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Context;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Context\Context::__construct
     * @covers Geissler\CSL\Context\Context::setName
     * @covers Geissler\CSL\Context\Context::getName
     */
    public function testSetAndGetName()
    {
        $this->assertInstanceOf($this->class, $this->object->setName('citation'));
        $this->assertEquals('citation', $this->object->getName());
    }

    /**
     * @covers Geissler\CSL\Context\Context::getName
     */
    public function testGetName()
    {
        $this->assertNull($this->object->getName());
    }

    /**
     * @covers Geissler\CSL\Context\Context::addStyle
     * @covers Geissler\CSL\Context\Context::getValue
     */
    public function testAddStyle()
    {
        $this->assertInstanceOf($this->class, $this->object->addStyle('test', true));
        $this->assertTrue($this->object->getValue('test'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::addCitation
     * @covers Geissler\CSL\Context\Context::getValue
     */
    public function testAddCitation()
    {
        $this->assertInstanceOf($this->class, $this->object->addCitation('testMe', 123));
        $this->assertEquals(123, $this->object->getValue('testMe', 'citation'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::addBibliography
     * @covers Geissler\CSL\Context\Context::getValue
     */
    public function testAddBibliography()
    {
        $this->assertInstanceOf($this->class, $this->object->addBibliography('testMe', 'blub'));
        $this->assertEquals('blub', $this->object->getValue('testMe', 'bibliography'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::getOptions
     */
    public function testGetOptions()
    {
        $this->assertInstanceOf($this->class, $this->object->setName('citation'));
        $this->assertInstanceOf($this->class, $this->object->addStyle('test', true));
        $this->assertInstanceOf($this->class, $this->object->addCitation('testMe', 123));
        $this->assertInternalType('array', $this->object->getOptions());
        $this->assertArrayHasKey('test', $this->object->getOptions());
        $this->assertArrayHasKey('testMe', $this->object->getOptions());
    }

    /**
     * @covers Geissler\CSL\Context\Context::getOptions
     */
    public function testGetOptions1()
    {
        $this->assertInstanceOf($this->class, $this->object->setName('bibliography'));
        $this->assertInstanceOf($this->class, $this->object->addStyle('test', true));
        $this->assertInstanceOf($this->class, $this->object->addCitation('testMe', 123));
        $this->assertInstanceOf($this->class, $this->object->addBibliography('testMore', 'blub'));
        $this->assertInternalType('array', $this->object->getOptions());
        $this->assertArrayHasKey('test', $this->object->getOptions());
        $this->assertArrayHasKey('testMore', $this->object->getOptions());
        $this->assertArrayNotHasKey('testMe', $this->object->getOptions());
    }

    /**
     * @covers Geissler\CSL\Context\Context::getOptions
     */
    public function testGetNoOptions()
    {
        $this->assertInstanceOf($this->class, $this->object->addStyle('test', true));
        $this->assertInstanceOf($this->class, $this->object->addCitation('testMe', 123));
        $this->assertInstanceOf($this->class, $this->object->addBibliography('testMore', 'blub'));
        $this->setExpectedException('ErrorException');
        $this->object->getOptions();
    }

    /**
     * @covers Geissler\CSL\Context\Context::getValue
     */
    public function testGetNoValue()
    {
        $this->assertEquals('', $this->object->getValue('test'));
        $this->assertEquals('', $this->object->getValue('test', 'citation'));
        $this->assertEquals('', $this->object->getValue('test', 'bibliography'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::enter
     * @covers Geissler\CSL\Context\Context::in
     */
    public function testEnter()
    {
        $this->assertInstanceOf($this->class, $this->object->enter('citation'));
        $this->assertTrue($this->object->in('citation'));
        $this->assertFalse($this->object->in('sort'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::enter
     * @covers Geissler\CSL\Context\Context::in
     * @covers Geissler\CSL\Context\Context::leave
     * @depends testEnter
     */
    public function testEnterAndLeave()
    {
        $this->assertInstanceOf($this->class, $this->object->enter('citation'));
        $this->assertTrue($this->object->in('citation'));
        $this->assertFalse($this->object->in('sort'));
        $this->assertInstanceOf($this->class, $this->object->leave());
    }

    /**
     * @covers Geissler\CSL\Context\Context::enter
     * @covers Geissler\CSL\Context\Context::in
     * @covers Geissler\CSL\Context\Context::leave
     * @depends testEnter
     */
    public function testEnterAndLeave1()
    {
        $this->assertInstanceOf($this->class, $this->object->enter('citation'));
        $this->assertTrue($this->object->in('citation'));
        $this->assertTrue($this->object->in('citation'));
        $this->assertInstanceOf($this->class, $this->object->enter('sort'));
        $this->assertTrue($this->object->in('sort'));
        $this->assertInstanceOf($this->class, $this->object->leave());
        $this->assertFalse($this->object->in('sort'));
        $this->assertTrue($this->object->in('citation'));
    }

    /**
     * @covers Geissler\CSL\Context\Context::enter
     * @covers Geissler\CSL\Context\Context::in
     * @covers Geissler\CSL\Context\Context::get
     * @depends testEnter
     */
    public function testGet()
    {
        $this->assertInstanceOf($this->class, $this->object->enter('citation', array('sort' => 'descending')));
        $this->assertTrue($this->object->in('citation'));
        $this->assertEquals('descending', $this->object->get('sort'));
        $this->assertNull($this->object->get('cake'));
    }
}
