<?php
namespace Geissler\CSL\Context;

use Geissler\CSL\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-07 at 00:46:56.
 */
class OptionsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Options
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Options;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Context\Options::set
     */
    public function testSet()
    {
        $layout =   '<citation
                        delimiter-precedes-last="always">
                     </citation>';
        $this->assertInstanceOf('\Geissler\CSL\Context\Options', $this->object->set('style', new \SimpleXMLElement($layout)));
        $this->assertEquals('always', Container::getContext()->getValue('delimiterPrecedesLast'));
    }
}
