<?php
namespace Geissler\CSL\Choose;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-12 at 13:55:38.
 */
class ChooseIfTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ChooseIf
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Choose\ChooseIf::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geissler\CSL\Choose\ChooseIf::hasAccessEmptyVariable
     * @todo   Implement testHasAccessEmptyVariable().
     */
    public function testHasAccessEmptyVariable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geissler\CSL\Choose\ChooseIf::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
