<?php
namespace Geissler\CSL\Choose;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-11 at 22:22:38.
 */
class ChooseElseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ChooseElse
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Choose\ChooseElse::validate
     */
    public function testValidate()
    {
        $layout =   '<else>
                        <text term="no date"/>
                      </else>';
        $this->initElement($layout);
        $this->assertTrue($this->object->validate());
    }

    protected function initElement($layout)
    {
        $xml = new \SimpleXMLElement($layout);
        $this->object   =   new ChooseElse($xml);
    }
}
