<?php
namespace Geissler\CSL\Choose;

use Geissler\CSL\Data\Data;
use Geissler\CSL\Container;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-11 at 22:29:42.
 */
class IsUncertainDateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var IsUncertainDate
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Choose\IsUncertainDate::__construct
     * @covers Geissler\CSL\Choose\IsUncertainDate::validate
     * @covers Geissler\CSL\Choose\IsUncertainDate::validateVariable
     */
    public function testValidate()
    {
        $json = '[
            {
                "id": "ITEM-1",
                "issued": {
                    "circa": 1,
                    "date-parts": [
                        [
                            2005,
                            12,
                            15
                        ]
                    ]
                },
                "type": "book"
            }]';
        $this->initElement('issued', $json);
        $this->assertTrue($this->object->validate());
    }

    /**
     * @covers Geissler\CSL\Choose\IsUncertainDate::__construct
     * @covers Geissler\CSL\Choose\IsUncertainDate::validate
     * @covers Geissler\CSL\Choose\IsUncertainDate::validateVariable
     */
    public function testValidateNot()
    {
        $json = '[
            {
                "id": "ITEM-1",
                "issued": {
                    "date-parts": [
                        [
                            2005,
                            12,
                            15
                        ]
                    ]
                },
                "type": "book"
            }]';
        $this->initElement('issued', $json);
        $this->assertFalse($this->object->validate());
    }

    protected function initElement($variable, $json)
    {
        $this->object   =   new IsUncertainDate($variable);

        $data   =   new Data();
        $data->set($json);
        Container::setData($data);
    }
}
