<?php
namespace Geissler\CSL\Bibliography;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-07 at 01:06:49.
 */
class BibliographyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Bibliography
     */
    protected $object;

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Bibliography\Bibliography::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
