<?php
namespace Geissler\CSL;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 13:34:16.
 */
class CSLTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CSL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CSL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\CSL::locale
     * @todo   Implement testLocale().
     */
    public function testLocale()
    {
        $this->assertInstanceOf('\Geissler\CSL\Locale', CSL::locale());
    }
}
