<?php
namespace Geissler\CSL\Style;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-06 at 19:16:54.
 */
class StyleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Style
     */
    protected $object;
    protected $class = '\Geissler\CSL\Style\Style';
    protected $dir;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Style;
        $this->dir  =   __DIR__ . '/../../../../../styles';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Style\Style::setDir
     */
    public function testSetDir()
    {
        $this->assertInstanceOf($this->class, $this->object->setDir('test'));
    }

    /**
     * @covers Geissler\CSL\Style\Style::readFile
     * @covers Geissler\CSL\Style\Style::setDir
     * @covers Geissler\CSL\Style\Style::readXml
     */
    public function testReadFile()
    {
        $this->assertInstanceOf($this->class, $this->object->setDir($this->dir));
        $this->assertInstanceOf($this->class, $this->object->readFile('chicago-annotated-bibliography'));
        $this->assertInstanceOf('\Geissler\CSL\Style\Citation', \Geissler\CSL\Container::getCitation());
        $this->assertInstanceOf('\Geissler\CSL\Style\Bibliography', \Geissler\CSL\Container::getBibliography());
        $this->assertInstanceOf('\Geissler\CSL\Locale\Locale', \Geissler\CSL\Container::getLocale());
    }

    /**
     * @covers Geissler\CSL\Style\Style::readFile
     * @covers Geissler\CSL\Style\Style::setDir
     * @covers Geissler\CSL\Style\Style::readXml
     */
    public function testReadFile1()
    {
        $this->assertInstanceOf($this->class, $this->object->setDir($this->dir));
        $this->assertInstanceOf($this->class, $this->object->readFile('revue-archeologique'));
        $this->assertInstanceOf('\Geissler\CSL\Style\Citation', \Geissler\CSL\Container::getCitation());
        $this->assertInstanceOf('\Geissler\CSL\Style\Bibliography', \Geissler\CSL\Container::getBibliography());
        $this->assertInstanceOf('\Geissler\CSL\Locale\Locale', \Geissler\CSL\Container::getLocale());
    }

    /**
     * @covers Geissler\CSL\Style\Style::readFile
     * @covers Geissler\CSL\Style\Style::setDir
     * @covers Geissler\CSL\Style\Style::readXml
     */
    public function testReadFile2()
    {
        $this->assertInstanceOf($this->class, $this->object->setDir($this->dir));
        $this->assertInstanceOf($this->class, $this->object->readFile('american-journal-of-archaeology'));
        $this->assertInstanceOf('\Geissler\CSL\Style\Citation', \Geissler\CSL\Container::getCitation());
        $this->assertInstanceOf('\Geissler\CSL\Style\Bibliography', \Geissler\CSL\Container::getBibliography());
        $this->assertInstanceOf('\Geissler\CSL\Locale\Locale', \Geissler\CSL\Container::getLocale());
    }

    /**
     * @covers Geissler\CSL\Style\Style::readFile
     */
    public function testReadFileError()
    {
        $this->setExpectedException('ErrorException');
        $this->object->readFile('not-there');
    }

    /**
     * @covers Geissler\CSL\Style\Style::readXml
     */
    public function testReadXml()
    {
        $xml    =   '<style
                        xmlns="http://purl.org/net/xbiblio/csl"
                        class="note"
                        version="1.0">
                    <info>
                      <id />
                      <title />
                      <updated>2009-08-10T04:49:00+09:00</updated>
                    </info>
                    <citation>
                      <layout>
                        <text value="Oops"/>
                      </layout>
                    </citation>
                    <bibliography
                        initialize-with=". ">
                      <layout>
                        <names variable="author">
                          <name />
                        </names>
                      </layout>
                    </bibliography>
                  </style>';
        $this->assertInstanceOf($this->class, $this->object->readXml(new \SimpleXMLElement($xml)));
    }

    /**
     * @covers Geissler\CSL\Style\Style::readXml
     */
    public function testReadXml1()
    {
        $xml    =   '<style
                        xmlns="http://purl.org/net/xbiblio/csl"
                        class="note"
                        version="1.0">
                    <info>
                      <id />
                      <title />
                      <updated>2009-08-10T04:49:00+09:00</updated>
                    </info>
                    <locale lang="fr">
                    </locale>
                    <citation>
                      <layout>
                        <text value="Oops"/>
                      </layout>
                    </citation>
                    <bibliography
                        initialize-with=". ">
                      <layout>
                        <names variable="author">
                          <name />
                        </names>
                      </layout>
                    </bibliography>
                  </style>';
        $this->assertInstanceOf($this->class, $this->object->readXml(new \SimpleXMLElement($xml)));
    }
}
