<?php
namespace Geissler\CSL\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-02 at 20:55:26.
 */
class DataTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Data;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\CSL\Data\Data::set
     */
    public function testDoNotSet()
    {
        $this->setExpectedException('ErrorException');
        Data::set('{');
    }

    /**
     * @covers Geissler\CSL\Data\Data::set
     */
    public function testSet()
    {
        $json = '[
    {
        "title": "His Book",
        "id": "ITEM-1",
        "type": "book"
    },
    {
        "volume": "101",
        "id": "ITEM-2",
        "type": "book"
    }
]';
        $this->assertTrue(Data::set($json));
    }

    /**
     * @covers Geissler\CSL\Data\Data::get
     * @depends testSet
     */
    public function testGet()
    {
        $this->assertInternalType('array', Data::get());
        $data = Data::get();
        $this->assertEquals('His Book', $data['title']);
        $this->assertEquals('ITEM-1', $data['id']);
    }

    /**
     * @covers Geissler\CSL\Data\Data::get
     * @covers Geissler\CSL\Data\Data::next
     * @depends testGet
     */
    public function testGetNext()
    {
        $this->assertTrue(Data::next());
        $this->assertInternalType('array', Data::get());
        $data = Data::get();
        $this->assertEquals('101', $data['volume']);
        $this->assertEquals('ITEM-2', $data['id']);
        $this->assertFalse(Data::next());
        $this->assertNull(Data::get());
    }

    /**
     * @covers Geissler\CSL\Data\Data::getVariable
     * @depends testSet
     */
    public function testGetVariable()
    {
        $json = '[
    {
        "title": "My Book",
        "edition": "5",
        "id": "ITEM-1",
        "type": "book"
    }]';
        $this->assertTrue(Data::set($json));
        $this->assertInternalType('array', Data::get());
        $this->assertEquals('My Book', Data::getVariable('title'));
        $this->assertNull(Data::getVariable('volume'));
    }

    /**
     * @covers Geissler\CSL\Data\Data::next
     * @depends testGet
     */
    public function testNext()
    {
        $json = '[
    {
        "title": "His Book",
        "id": "ITEM-1",
        "type": "book"
    },
    {
        "volume": "101",
        "id": "ITEM-2",
        "type": "book"
    }
]';
        $this->assertTrue(Data::set($json));
        $this->assertTrue(Data::next());
        $this->assertFalse(Data::next());
    }
}
